2014/09/22 11:12:42 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.abcd" is not defined.' in /home/user/nginx/www/yiitest/framework/base/CComponent.php:130
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/base/CModule.php(105): CComponent->__get('abcd')
#1 /home/user/nginx/www/yiitest/protected/controllers/BookController.php(12): CModule->__get('abcd')
#2 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): BookController->actionList()
#3 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('list')
#7 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('book/list')
#8 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yiitest/index.php?r=book/list
---
2014/09/22 11:12:44 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.abcd" is not defined.' in /home/user/nginx/www/yiitest/framework/base/CComponent.php:130
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/base/CModule.php(105): CComponent->__get('abcd')
#1 /home/user/nginx/www/yiitest/protected/controllers/BookController.php(12): CModule->__get('abcd')
#2 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): BookController->actionList()
#3 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('list')
#7 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('book/list')
#8 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yiitest/index.php?r=book/list
---
2014/09/22 12:25:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:25:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:25:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:26:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:29:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:29:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:31:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:32:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:32:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 12:32:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /home/user/nginx/www/yiitest/framework/db/CDbConnection.php:382
Stack trace:
#0 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/user/nginx/www/yiitest/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/user/nginx/www/yiitest/framework/base/CModule.php(387): CDbConnection->init()
#3 /home/user/nginx/www/yiitest/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /home/user/nginx/www/yiitest/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /home/user/nginx/www/yiitest/framework/web/CFormModel.php(39): ModelCode->init()
#6 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /home/user/nginx/www/yiitest/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /home/user/nginx/www/yiitest/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /home/user/nginx/www/yiitest/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /home/user/nginx/www/yiitest/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /home/user/nginx/www/yiitest/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(282): CController->run('index')
#13 /home/user/nginx/www/yiitest/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /home/user/nginx/www/yiitest/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /home/user/nginx/www/yiitest/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2014/09/22 15:05:23 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:31 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:32 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:33 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:34 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:35 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:07:36 [error] [exception.CException] exception 'CException' with message 'UserController cannot find the requested view "login".' in /home/user/github/yii-example/framework/web/CController.php:878
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(782): CController->renderPartial('login', NULL, true)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(13): CController->render('login')
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=user/login
---
2014/09/22 15:09:01 [error] [php] Undefined variable: formAction (/home/user/github/yii-example/themes/example/views/user/login.php:9)
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(869): UserController->renderFile()
#1 /home/user/github/yii-example/framework/web/CController.php(782): UserController->renderPartial()
#2 /home/user/github/yii-example/protected/controllers/UserController.php(13): UserController->render()
#3 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#4 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#6 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=user/login
in /home/user/github/yii-example/themes/example/views/user/login.php (9)
in /home/user/github/yii-example/protected/controllers/UserController.php (13)
in /home/user/github/yii-example/index.php (13)
2014/09/22 15:10:44 [error] [php] Undefined variable: model (/home/user/github/yii-example/themes/example/views/user/login.php:12)
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(869): UserController->renderFile()
#1 /home/user/github/yii-example/framework/web/CController.php(782): UserController->renderPartial()
#2 /home/user/github/yii-example/protected/controllers/UserController.php(13): UserController->render()
#3 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#4 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#6 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=user/login
in /home/user/github/yii-example/themes/example/views/user/login.php (12)
in /home/user/github/yii-example/protected/controllers/UserController.php (13)
in /home/user/github/yii-example/index.php (13)
2014/09/22 15:10:45 [error] [php] Undefined variable: model (/home/user/github/yii-example/themes/example/views/user/login.php:12)
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(869): UserController->renderFile()
#1 /home/user/github/yii-example/framework/web/CController.php(782): UserController->renderPartial()
#2 /home/user/github/yii-example/protected/controllers/UserController.php(13): UserController->render()
#3 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#4 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#6 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=user/login
in /home/user/github/yii-example/themes/example/views/user/login.php (12)
in /home/user/github/yii-example/protected/controllers/UserController.php (13)
in /home/user/github/yii-example/index.php (13)
2014/09/23 09:49:17 [error] [exception.CException] exception 'CException' with message 'UserController and its behaviors do not have a method or closure named "getCommandBuilder".' in /home/user/github/yii-example/framework/base/CComponent.php:266
Stack trace:
#0 /home/user/github/yii-example/framework/db/ar/CActiveRecord.php(1455): CComponent->__call('getCommandBuild...', Array)
#1 /home/user/github/yii-example/framework/db/ar/CActiveRecord.php(1455): UserController->getCommandBuilder()
#2 /home/user/github/yii-example/protected/controllers/UserController.php(26): CActiveRecord->find('username=:usern...', Array)
#3 /home/user/github/yii-example/protected/controllers/UserController.php(11): UserController->_handleLogin()
#4 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#5 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('login')
#9 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#10 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /home/user/github/yii-example/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/user/login
HTTP_REFERER=http://yiiexample.com/user/login
---
2014/09/23 10:11:45 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "isSocial".' in /home/user/github/yii-example/framework/base/CComponent.php:266
Stack trace:
#0 /home/user/github/yii-example/framework/db/ar/CActiveRecord.php(227): CComponent->__call('isSocial', Array)
#1 /home/user/github/yii-example/themes/example/views/layouts/header.php(23): CActiveRecord->__call('isSocial', Array)
#2 /home/user/github/yii-example/themes/example/views/layouts/header.php(23): User->isSocial('1')
#3 /home/user/github/yii-example/framework/web/CBaseController.php(126): require('/home/user/gith...')
#4 /home/user/github/yii-example/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/user/gith...', Array, true)
#5 /home/user/github/yii-example/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/home/user/gith...', Array, true)
#6 /home/user/github/yii-example/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('      ')
#7 /home/user/github/yii-example/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('      ')
#8 /home/user/github/yii-example/framework/web/CBaseController.php(206): COutputProcessor->run()
#9 /home/user/github/yii-example/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#10 /home/user/github/yii-example/themes/example/views/layouts/main.php(18): CBaseController->endContent()
#11 /home/user/github/yii-example/framework/web/CBaseController.php(126): require('/home/user/gith...')
#12 /home/user/github/yii-example/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/user/gith...', Array, true)
#13 /home/user/github/yii-example/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/home/user/gith...', Array, true)
#14 /home/user/github/yii-example/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#15 /home/user/github/yii-example/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#16 /home/user/github/yii-example/framework/web/CBaseController.php(206): COutputProcessor->run()
#17 /home/user/github/yii-example/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#18 /home/user/github/yii-example/protected/views/layouts/column1.php(6): CBaseController->endContent()
#19 /home/user/github/yii-example/framework/web/CBaseController.php(126): require('/home/user/gith...')
#20 /home/user/github/yii-example/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/user/gith...', Array, true)
#21 /home/user/github/yii-example/framework/web/CController.php(784): CBaseController->renderFile('/home/user/gith...', Array, true)
#22 /home/user/github/yii-example/protected/controllers/SiteController.php(32): CController->render('index')
#23 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#24 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#25 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#26 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#27 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('')
#28 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#29 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#30 /home/user/github/yii-example/index.php(13): CApplication->run()
#31 {main}
REQUEST_URI=/
HTTP_REFERER=http://yiiexample.com/user/login
---
2014/09/23 10:13:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/example/css/images/logo.png".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('themes/example/...')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/themes/example/css/images/logo.png
HTTP_REFERER=http://yiiexample.com/
---
2014/09/23 10:13:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/example/css/images/logo_split.png".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('themes/example/...')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/themes/example/css/images/logo_split.png
HTTP_REFERER=http://yiiexample.com/
---
2014/09/23 10:13:14 [error] [php] Undefined variable: Yii (/home/user/github/yii-example/protected/controllers/UserController.php:26)
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#1 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#2 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#3 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#5 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/user/logout
in /home/user/github/yii-example/protected/controllers/UserController.php (26)
in /home/user/github/yii-example/index.php (13)
2014/09/23 10:13:38 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "redirect".' in /home/user/github/yii-example/framework/base/CComponent.php:266
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/UserController.php(26): CComponent->__call('redirect', Array)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(26): CWebApplication->redirect(Array)
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogout()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('logout')
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/logout')
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/user/logout
HTTP_REFERER=http://yiiexample.com/
---
2014/09/23 10:13:52 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(80): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (80)
in /home/user/github/yii-example/index.php (13)
2014/09/23 10:15:42 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(80): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (80)
in /home/user/github/yii-example/index.php (13)
2014/09/23 10:15:43 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(80): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (80)
in /home/user/github/yii-example/index.php (13)
2014/09/23 10:15:44 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(80): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (80)
in /home/user/github/yii-example/index.php (13)
2014/09/23 10:15:46 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(80): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (80)
in /home/user/github/yii-example/index.php (13)
2014/09/24 14:06:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/09/24 15:25:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/09/25 10:07:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/09/25 15:07:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/09/26 09:06:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/09/26 09:06:58 [error] [php] Undefined variable: message (/home/user/github/yii-example/themes/example/views/user/login.php:3)
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(869): UserController->renderFile()
#1 /home/user/github/yii-example/framework/web/CController.php(782): UserController->renderPartial()
#2 /home/user/github/yii-example/protected/controllers/UserController.php(13): UserController->render()
#3 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#4 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#6 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/user/login
in /home/user/github/yii-example/themes/example/views/user/login.php (3)
in /home/user/github/yii-example/protected/controllers/UserController.php (13)
in /home/user/github/yii-example/index.php (13)
2014/09/26 10:36:46 [error] [php] Missing argument 2 for User::__construct(), called in /home/user/github/yii-example/framework/db/ar/CActiveRecord.php on line 395 and defined (/home/user/github/yii-example/protected/models/User.php:15)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/UserController.php(56): model()
#1 /home/user/github/yii-example/protected/controllers/UserController.php(24): UserController->_handleRegister()
#2 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#3 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#4 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#5 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#7 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#8 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/user/register
in /home/user/github/yii-example/protected/models/User.php (15)
in /home/user/github/yii-example/protected/models/User.php (110)
in /home/user/github/yii-example/protected/controllers/UserController.php (56)
2014/09/26 10:53:40 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "hassPassword".' in /home/user/github/yii-example/framework/base/CComponent.php:266
Stack trace:
#0 /home/user/github/yii-example/framework/db/ar/CActiveRecord.php(227): CComponent->__call('hassPassword', Array)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(56): CActiveRecord->__call('hassPassword', Array)
#2 /home/user/github/yii-example/protected/controllers/UserController.php(56): User->hassPassword('abc123_')
#3 /home/user/github/yii-example/protected/controllers/UserController.php(24): UserController->_handleRegister()
#4 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#5 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('register')
#9 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#10 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /home/user/github/yii-example/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/user/register
HTTP_REFERER=http://yiiexample.com/user/register
---
2014/09/26 10:53:56 [error] [php] Undefined variable: identity (/home/user/github/yii-example/protected/controllers/UserController.php:62)
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /home/user/github/yii-example/framework/web/CController.php(286): UserController->runAction()
#2 /home/user/github/yii-example/framework/web/CController.php(265): UserController->runActionWithFilters()
#3 /home/user/github/yii-example/framework/web/CWebApplication.php(282): UserController->run()
#4 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#5 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#6 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/user/register
in /home/user/github/yii-example/protected/controllers/UserController.php (62)
in /home/user/github/yii-example/protected/controllers/UserController.php (24)
in /home/user/github/yii-example/index.php (13)
2014/09/26 10:55:31 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "hassPassword".' in /home/user/github/yii-example/framework/base/CComponent.php:266
Stack trace:
#0 /home/user/github/yii-example/framework/db/ar/CActiveRecord.php(227): CComponent->__call('hassPassword', Array)
#1 /home/user/github/yii-example/protected/controllers/UserController.php(61): CActiveRecord->__call('hassPassword', Array)
#2 /home/user/github/yii-example/protected/controllers/UserController.php(61): User->hassPassword('abc123_')
#3 /home/user/github/yii-example/protected/controllers/UserController.php(24): UserController->_handleRegister()
#4 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#5 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /home/user/github/yii-example/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /home/user/github/yii-example/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('register')
#9 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#10 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /home/user/github/yii-example/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/user/register
HTTP_REFERER=http://yiiexample.com/user/register
---
2014/09/26 11:00:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/example/css/images/logo.png".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('themes/example/...')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/themes/example/css/images/logo.png
HTTP_REFERER=http://yiiexample.com/
---
2014/09/26 11:00:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/example/css/images/logo_split.png".' in /home/user/github/yii-example/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('themes/example/...')
#1 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/user/github/yii-example/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/themes/example/css/images/logo_split.png
HTTP_REFERER=http://yiiexample.com/
---
2014/09/26 11:00:53 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(81): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (81)
in /home/user/github/yii-example/index.php (13)
2014/09/26 11:01:02 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (/home/user/github/yii-example/framework/YiiBase.php:427)
Stack trace:
#0 /home/user/github/yii-example/protected/controllers/SiteController.php(81): spl_autoload_call()
#1 /home/user/github/yii-example/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#2 /home/user/github/yii-example/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/user/github/yii-example/framework/web/CController.php(286): SiteController->runAction()
#4 /home/user/github/yii-example/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /home/user/github/yii-example/framework/web/CWebApplication.php(282): SiteController->run()
#6 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/user/github/yii-example/index.php(13): CWebApplication->run()
REQUEST_URI=/site/login
in /home/user/github/yii-example/protected/controllers/SiteController.php (81)
in /home/user/github/yii-example/index.php (13)
2014/09/26 11:01:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "register".' in /home/user/github/yii-example/framework/web/CController.php:483
Stack trace:
#0 /home/user/github/yii-example/framework/web/CController.php(270): CController->missingAction('register')
#1 /home/user/github/yii-example/framework/web/CWebApplication.php(282): CController->run('register')
#2 /home/user/github/yii-example/framework/web/CWebApplication.php(141): CWebApplication->runController('site/register')
#3 /home/user/github/yii-example/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /home/user/github/yii-example/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/register
---
